# Используем slim-образ с Python 3.12
FROM python:3.12-slim

# 1. Обновляем индекс пакетов с повтором при ошибке


# 2. Установка Python-зависимостей с зеркалом PyPI (если нужно)
RUN pip install --no-cache-dir \
    python-multipart \
    requests \
    fastapi \
    uvicorn \
    pydantic

# 3. Создание структуры проекта
RUN useradd -m -u 1000 appuser

# 4. Копирование файлов (оптимизированный порядок)
COPY --chown=appuser:appuser ./src/qf.py ./src/ta.py ./src/processing_text.py /app/
COPY --chown=appuser:appuser ./text_processing_api/text_processing_api.py /app/


# 5. Настройка окружения
WORKDIR /app
USER appuser

# 6. Запуск приложения
# Запуск приложения с оптимизированными параметрами Gunicorn
CMD ["uvicorn", \
    "text_processing_api:app", \
    "--host", "0.0.0.0", \
    "--port", "5002", \
    "--timeout-keep-alive", "300"]