# Используем официальный образ Python с CUDA (для GPU)
FROM python:3.12.8-slim

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-rus

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY ../containers/api/ /app/

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    gunicorn \
    pytesseract \
    opencv-python-headless \  
    numpy \
    requests


CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", \
    "--bind", "0.0.0.0:5000", \
    "--timeout", "300", \
    "--max-requests", "1000", \
    "--max-requests-jitter", "50", \
    "tesseract_api:app"]